# Generated by Django 4.0.2 on 2023-04-16 23:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cash_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_uuid', models.UUIDField(default=None)),
                ('to_uuid', models.UUIDField(default=None)),
                ('balance', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
