# Generated by Django 4.0.2 on 2023-04-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_account', '0003_cashtransactions_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashTransactions',
            new_name='CashTransaction',
        ),
    ]
