# Generated by Django 4.0.2 on 2023-04-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_account', '0004_rename_cashtransactions_cashtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='status',
            field=models.CharField(choices=[('error', 'Error!'), ('ongoing', 'Ongoing...'), ('completed', 'Completed'), ('cancelled', 'Canceled!')], default='error', max_length=100),
        ),
    ]
