# Generated by Django 4.0.2 on 2023-04-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_account', '0005_alter_cashtransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='from_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='to_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='status',
            field=models.CharField(choices=[('error', 'Error!'), ('ongoing', 'Ongoing...'), ('completed', 'Completed'), ('cancelled', 'Canceled!')], default='ongoing', max_length=100),
        ),
    ]
