# Generated by Django 4.1.4 on 2023-04-10 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash_account', '0001_initial'),
        ('bankz_auth', '0002_remove_bankzuserchild_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankzuserchild',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='cash_account.cashaccount'),
        ),
        migrations.AlterField(
            model_name='bankzuserchild',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='bankz_auth.bankzuserparent'),
        ),
        migrations.AlterField(
            model_name='bankzuserparent',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='cash_account.cashaccount'),
        ),
        migrations.DeleteModel(
            name='CashAccount',
        ),
    ]
