# Generated by Django 4.0.2 on 2023-04-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_account', '0002_cashtransactions'),
        ('bankz_auth', '0003_alter_bankzuserchild_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankzuserchild',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='cash_account.CashAccount'),
        ),
        migrations.AlterField(
            model_name='bankzuserparent',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='cash_account.CashAccount'),
        ),
    ]
