# Generated by Django 4.0.2 on 2022-12-09 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bankz_auth', '0002_rename_newusermodel_bankzuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankzuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
