# Generated by Django 4.1.4 on 2022-12-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankz_auth', '0004_bankzuserchild_bankzuserparent_delete_bankzuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankzuserchild',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankz_auth.bankzuserparent'),
        ),
    ]
