# Generated by Django 4.1.4 on 2022-12-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankz_auth', '0006_bankzuserparent_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankzuserchild',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
