# Generated by Django 4.1.4 on 2022-12-12 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankz_auth', '0007_bankzuserchild_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankzuserchild',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bankzuserchild',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bankzuserparent',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bankzuserparent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bankzuserparent',
            name='user',
        ),
        migrations.AddField(
            model_name='bankzuserparent',
            name='childs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankzuserchild',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankZUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bankzuserchild',
            name='bankzuser_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bankz_auth.bankzuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankzuserparent',
            name='accounts',
            field=models.ManyToManyField(to='bankz_auth.cashaccount'),
        ),
        migrations.AddField(
            model_name='bankzuserparent',
            name='bankzuser_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bankz_auth.bankzuser'),
            preserve_default=False,
        ),
    ]
