# Generated by Django 4.1.4 on 2022-12-12 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankz_auth', '0009_alter_bankzuserchild_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankzuserchild',
            name='bankzuser_ptr',
        ),
        migrations.RemoveField(
            model_name='bankzuserparent',
            name='bankzuser_ptr',
        ),
        migrations.RemoveField(
            model_name='bankzuserparent',
            name='childs',
        ),
        migrations.AddField(
            model_name='bankzuserchild',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bankzuserchild',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankzuserparent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='bankzuserparent',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BankZUser',
        ),
    ]
