# Generated by Django 4.1.4 on 2022-12-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankz_auth', '0010_remove_bankzuserchild_bankzuser_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankzuserchild',
            name='parent',
        ),
    ]
